### ISSUE TITLE
error when opening TED talk plugin

### ISSUE THREAD

**Issue by janvda** [janvda/docker-kodi#1]
The following is seen in the log file: 
```
2023-06-11 22:35:27.192 T:343      INFO <general>: CAddonMgr::FindAddon: plugin.video.ted.talks v5.0.0 installed
2023-06-11 22:35:27.294 T:148   WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2023-06-11 22:35:39.121 T:148      INFO <general>: Skipped 2 duplicate messages..
2023-06-11 22:35:39.121 T:148      INFO <general>: Loading skin file: DialogAddonSettings.xml, load type: KEEP_IN_MEMORY
2023-06-11 22:35:56.329 T:148     ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-06-11 22:35:56.392 T:366      INFO <general>: initializing python engine.
2023-06-11 22:35:56.898 T:366      INFO <general>: [ADDON] Initialized TED Talks v5.0.0 using Python: 3.9.7 (default, Sep 10 2021, 14:59:43) 
                                                   [GCC 11.2.0]'
2023-06-11 22:35:58.703 T:366      INFO <general>: CPythonInvoker(12, /home/jan/.kodi/addons/plugin.video.ted.talks/default.py): script successfully run
2023-06-11 22:35:58.790 T:366      INFO <general>: Python interpreter stopped
2023-06-11 22:36:01.192 T:369      INFO <general>: initializing python engine.
2023-06-11 22:36:01.565 T:369      INFO <general>: [ADDON] Initialized TED Talks v5.0.0 using Python: 3.9.7 (default, Sep 10 2021, 14:59:43) 
                                                   [GCC 11.2.0]'
2023-06-11 22:36:03.696 T:369      INFO <general>: CPythonInvoker(13, /home/jan/.kodi/addons/plugin.video.ted.talks/default.py): script successfully run
2023-06-11 22:36:03.778 T:369      INFO <general>: Python interpreter stopped
2023-06-11 22:37:03.992 T:374      INFO <general>: initializing python engine.
2023-06-11 22:37:04.307 T:374      INFO <general>: [ADDON] Initialized TED Talks v5.0.0 using Python: 3.9.7 (default, Sep 10 2021, 14:59:43) 
                                                   [GCC 11.2.0]'
2023-06-11 22:37:06.276 T:374      INFO <general>: [ADDON] TED Talks v5.0.0 - GET https://www.ted.com/talks/alona_fyshe_does_ai_actually_understand_us?rss=172BB350-0205
2023-06-11 22:37:07.237 T:374     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'Exception' object has no attribute 'message'
                                                   Traceback (most recent call last):
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 17, in get_video_details
                                                       m3u8_url, title, speaker, plot, talk_json = talk_scraper.get_talk(talk_html, self.logger)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/model/talk_scraper.py", line 14, in get_talk
                                                       raise Exception('Could not parse HTML.')
                                                   Exception: Could not parse HTML.
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/default.py", line 14, in <module>
                                                       ted_talks.Main(args_map=args_map).run()
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 336, in run
                                                       modes[mode].run(self.args_map)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 148, in run
                                                       self.run_internal(args)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 166, in run_internal
                                                       self.ui.playVideo(args['url'], args['icon'] if 'icon' in args else None)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 71, in playVideo
                                                       playlist, title, subs, info_labels = self.ted_talks.get_video_details(url=url, subs_language=subs_language)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 19, in get_video_details
                                                       raise type(e)(e.message + "\nfor url '%s'" % (url))
                                                   AttributeError: 'Exception' object has no attribute 'message'
                                                   -->End of Python script error report<--
                                                   
2023-06-11 22:37:07.320 T:374      INFO <general>: Python interpreter stopped
2023-06-11 22:37:07.344 T:148     ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ted.talks/?mode=playVideo&url=https%3A%2F%2Fwww.ted.com%2Ftalks%2Falona_fyshe_does_ai_ac
tually_understand_us%3Frss%3D172BB350-0205]
2023-06-11 22:37:07.378 T:148      INFO <general>: CVideoPlayer::CloseFile()
2023-06-11 22:37:07.386 T:252      INFO <general>: CVideoPlayer::OnExit()
2023-06-11 22:37:07.386 T:252      INFO <general>: Closing stream player 1
2023-06-11 22:37:07.386 T:252      INFO <general>: Waiting for audio thread to exit
```

**Comment by janvda** [comment]
similar issue is reported here:
* https://github.com/janvda/balena-kodi-etcetera/issues/4

**Comment by janvda** [comment]
Still having same issue on latest install (kodi 2.2.1)

```
2025-04-26 10:24:42.848 T:52628    info <general>: [ADDON] Initialized TED Talks v5.0.0 using Python: 3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0]'
2025-04-26 10:24:44.709 T:52628    info <general>: [ADDON] TED Talks v5.0.0 - GET https://www.ted.com/talks/kasley_killam_why_social_health_is_key_to_happiness_and_longevity?rss=172BB350-0205
2025-04-26 10:24:45.585 T:52628   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'Exception' object has no attribute 'message'
                                                   Traceback (most recent call last):
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 17, in get_video_details
                                                       m3u8_url, title, speaker, plot, talk_json = talk_scraper.get_talk(talk_html, self.logger)
                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/model/talk_scraper.py", line 14, in get_talk
                                                       raise Exception('Could not parse HTML.')
                                                   Exception: Could not parse HTML.
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/default.py", line 14, in <module>
                                                       ted_talks.Main(args_map=args_map).run()
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 336, in run
                                                       modes[mode].run(self.args_map)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 148, in run
                                                       self.run_internal(args)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 166, in run_internal
                                                       self.ui.playVideo(args['url'], args['icon'] if 'icon' in args else None)
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks.py", line 71, in playVideo
                                                       playlist, title, subs, info_labels = self.ted_talks.get_video_details(url=url, subs_language=subs_language)
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/home/jan/.kodi/addons/plugin.video.ted.talks/resources/lib/ted_talks_scraper.py", line 19, in get_video_details
                                                       raise type(e)(e.message + "\nfor url '%s'" % (url))
                                                                     ^^^^^^^^^
                                                   AttributeError: 'Exception' object has no attribute 'message'
                                                   -->End of Python script error report<--
                                                   
2025-04-26 10:24:45.736 T:52565   error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.ted.talks/?mode=playVideo&url=https%3A%2F%2Fwww.ted.com%2Ftalks%2Fkasley_killam_why_social_health_is_key_to_happiness_and_longevity%3Frss%3D172BB350-0205]
```

I also noticed that at the same time the following error is logged by the container:

```
../Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time
```

the full container log
```
libva info: VA-API version 1.20.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
../Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

../Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

../Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

../Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

../Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time
```

**Comment by janvda** [comment]
I think this problem is also reported here:
* https://github.com/moreginger/xbmc-plugin.video.ted.talks/issues/80

and  this is a fix for that problem:
* https://github.com/Kevwag-Kodi-Forks/plugin.video.ted.talks/releases/tag/v5.0.1
